### ISSUE TITLE
CUDA_HOME environment variable is not set

### ISSUE THREAD

**Issue by JunMa11** [shirgur/UMIS#5]
Dear @shirgur ,

Thanks for sharing the great work.

When I installed the `morphologicalpool` by `python morphologicalpool/setup.py install`, following error occurred:

```python
Traceback (most recent call last):
  File "morphologicalpool/setup.py", line 9, in <module>
    'morphpool_cuda_kernel.cu',
  File "/home/mia/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 479, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/mia/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 558, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/home/mia/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1216, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```
My environment is ubuntu 18.04 + cuda 10.0.
I have installed the `cuda` and `cudnn` before installing the pytorch.

I can't find any useful solutions by google.

Could you share your insight about how to solve this problem?

Looking forward to your reply.
Best regards,
Jun

**Comment by JunMa11** [comment]
BTW, the `train_sup.py` works on the same PC

**Comment by JunMa11** [comment]
This is because I didn't set the cuda path after installing it.
Now it is fixed.
